#define FT_LE_HOST_TEST
#include "../../../bluetooth/port_rtthread/bt_le_audio_unicast.c"
static unsigned notification_count;
uint8_t att_server_register_can_send_now_callback(btstack_context_callback_registration_t *r, hci_con_handle_t h) { (void)r; (void)h; return 0; }
uint8_t att_server_notify(hci_con_handle_t h, uint16_t a, const uint8_t *p, uint16_t n) {
    (void)h; (void)a; (void)p; assert(n <= 64); notification_count++; return 0;
}
uint8_t gap_disconnect(hci_con_handle_t h) { (void)h; return 0; }
uint8_t gap_cis_accept(hci_con_handle_t h) { (void)h; return 0; }
uint8_t gap_cis_reject(hci_con_handle_t h) { (void)h; return 0; }
void hci_add_event_handler(btstack_packet_callback_registration_t *r) { (void)r; }
void hci_register_iso_packet_handler(btstack_packet_handler_t h) { (void)h; }
void hci_dump_log(int level, const char *fmt, ...) { (void)level; (void)fmt; }
int main(void) {
    s_acl_handle=1; s_cp_notify=1;
    for (unsigned i=0;i<2;i++) { s_ase[i].ase_id=i+1; ft_le_ase_reset(&s_ase[i]); s_ase[i].notify_on=1; }
    /* Standard Config Codec: opcode, count, then two variable-length ASEs. */
    uint8_t codec[] = {1,2,
        1,2,2,6,0,0,0,0,16, 2,1,8, 2,2,1, 5,3,1,0,0,0, 3,4,120,0,
        2,2,2,6,0,0,0,0,16, 2,1,8, 2,2,1, 5,3,2,0,0,0, 3,4,120,0};
    ft_le_control_point(codec,sizeof(codec));
    assert(s_ase[0].state==1 && s_ase[1].state==1);
    assert(s_ase[1].chan_alloc==2);
    uint8_t encoded[64];
    assert(ft_le_ase_encode(&s_ase[0],encoded)==41);
    assert(encoded[19]==6 && encoded[24]==16);
    uint8_t short_read[5];
    assert(ft_le_audio_att_read(s_ase_value_handle[0],20,short_read,5)==5);
    uint8_t qos[]={2,2,
        1,0,0,0x10,0x27,0,0,2,120,0,2,20,0,0x40,0x9c,0,
        2,0,1,0x10,0x27,0,0,2,120,0,2,20,0,0x40,0x9c,0};
    ft_le_control_point(qos,sizeof(qos));
    assert(s_ase[0].state==2 && s_ase[1].state==2);
    assert(s_ase[0].pres_delay_us==40000);
    assert(ft_le_ase_encode(&s_ase[1],encoded)==17 && encoded[3]==1);
    uint8_t enable[]={3,2,1,0,2,0};
    ft_le_control_point(enable,sizeof(enable));
    assert(s_ase[0].state==3 && s_streaming==0);
    s_ase[0].established=1; s_ase[0].state=4; s_ase[0].cis_handle=0x40;
    uint8_t iso[128]={0x40,0x20,124,0,1,0,120,0};
    for(unsigned i=8;i<128;i++) iso[i]=(uint8_t)i;
    ft_le_iso_handler(HCI_ISO_DATA_PACKET,0,iso,sizeof(iso));
    assert(produced_len==123 && produced[0]==121 && produced[122]==127);
    uint8_t disable[]={5,1,1};
    ft_le_control_point(disable,sizeof(disable));
    assert(s_ase[0].state==2);
    uint8_t release[]={8,2,1,2};
    ft_le_control_point(release,sizeof(release));
    assert(s_ase[0].state==0 && s_ase[0].notify_on==1);
    while(s_ntf_rd!=s_ntf_wr) ft_le_send_next(NULL);
    assert(notification_count>0);
    /* Truncated multi-ASE input must not partly configure an endpoint. */
    ft_le_control_point(codec,sizeof(codec)-1);
    assert(s_ase[0].state==0 && s_ase[1].state==0);
    codec[13]=7; /* 44.1 kHz is outside the decoder contract. */
    ft_le_control_point(codec,sizeof(codec));
    assert(s_ase[0].state==0);
    assert(s_ntf[(s_ntf_wr-1)%FT_NOTIFY_MAX].value[3]!=0);
    /* Full GATT database walk and PAC LTV lengths, using generated bytes. */
    unsigned p=1, pac_found=0, cp_found=0, role_found=0;
    while(profile_data[p] || profile_data[p+1]) {
        unsigned len=little_endian_read_16(profile_data,p);
        assert(len>=8 && p+len<=sizeof(profile_data));
        unsigned uuid=little_endian_read_16(profile_data,p+6);
        if(uuid==0x2bc9) {
            const uint8_t *v=&profile_data[p+8];
            assert(v[0]==1 && v[1]==6 && v[6]==13 && len==29);
            unsigned q=7;
            while(q<20) { assert(v[q]>=1 && q+1+v[q]<=20); q+=1+v[q]; }
            assert(q==20 && v[q]==0 && v[7]==3 && v[9]==0x80 && v[10]==0);
            pac_found++;
        }
        if(uuid==0x2803 && profile_data[p+11]==0xc6 && profile_data[p+12]==0x2b) {
            assert((profile_data[p+8]&0x14)==0x14); cp_found++;
        }
        if(uuid==0x2b51) { assert(profile_data[p+8]==8); role_found++; }
        p+=len;
    }
    assert(pac_found==1 && cp_found==1 && role_found==1);
    /* Android rejects Available Audio Contexts without a CCC descriptor. */
    uint16_t contexts_ccc = ATT_CHARACTERISTIC_ORG_BLUETOOTH_CHARACTERISTIC_AVAILABLE_AUDIO_CONTEXTS_01_CLIENT_CONFIGURATION_HANDLE;
    unsigned ccc_present = 0;
    for (unsigned q=1; profile_data[q] || profile_data[q+1]; q+=little_endian_read_16(profile_data,q)) {
        if (little_endian_read_16(profile_data,q+4)==contexts_ccc) {
            assert(little_endian_read_16(profile_data,q+6)==0x2902);
            ccc_present++;
        }
    }
    assert(ccc_present==1);
    uint8_t subscribe[]={1,0}, read_ccc[2]={0};
    assert(ft_le_audio_att_write(1,contexts_ccc,subscribe,2)==0);
    assert(ft_le_audio_att_read(contexts_ccc,0,read_ccc,2)==2 && read_ccc[0]==1);
    uint8_t volume_cmd[]={4,0,255};
    uint16_t vc=ATT_CHARACTERISTIC_ORG_BLUETOOTH_CHARACTERISTIC_VOLUME_CONTROL_POINT_01_VALUE_HANDLE;
    assert(ft_le_audio_att_write(1,vc,volume_cmd,3)==0);
    assert(FT_ALINK->volume_percent==100 && s_volume[2]==1);
    assert(ft_le_audio_att_write(1,vc,volume_cmd,3)==0x80);
    uint8_t mute_cmd[]={6,1};
    assert(ft_le_audio_att_write(1,vc,mute_cmd,2)==0);
    assert(FT_ALINK->volume_percent==0 && s_volume[2]==2);
    puts("PASS: multi-ASE codec/QoS, state wire format, partial ATT read, ISO tail, disable/release, truncated request");
    return 0;
}
