#ifndef FEATHER_UI_ICONS_H
#define FEATHER_UI_ICONS_H

#include "feather_ui.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef uint16_t fui_icon_id_t;

enum
{
    FUI_ICON_NONE = 0,

    FUI_ICON_APP_SETTINGS,
    FUI_ICON_APP_FILES,
    FUI_ICON_APP_GALLERY,
    FUI_ICON_APP_AUDIO,
    FUI_ICON_APP_RECORDER,
    FUI_ICON_APP_SYSTEM,
    FUI_ICON_APP_USB_SD,
    FUI_ICON_APP_WIFI,
    FUI_ICON_APP_BLUETOOTH,
    FUI_ICON_APP_MEDIA,

    FUI_ICON_SETTING_DISPLAY,
    FUI_ICON_SETTING_AUDIO,
    FUI_ICON_SETTING_WIFI,
    FUI_ICON_SETTING_BLUETOOTH,
    FUI_ICON_SETTING_STORAGE,
    FUI_ICON_SETTING_USB,
    FUI_ICON_SETTING_TIME_LANGUAGE,
    FUI_ICON_SETTING_PERSONALIZATION,
    FUI_ICON_SETTING_SYSTEM,
    FUI_ICON_SETTING_ABOUT,

    FUI_ICON_BRIGHTNESS,
    FUI_ICON_ROTATION,
    FUI_ICON_OUTPUT_VOLUME,
    FUI_ICON_INPUT_GAIN,
    FUI_ICON_SAMPLE_RATE,
    FUI_ICON_SAMPLE_DEPTH,
    FUI_ICON_CHANNELS,
    FUI_ICON_SPEAKER,
    FUI_ICON_MICROPHONE,
    FUI_ICON_WIFI,
    FUI_ICON_BLUETOOTH,
    FUI_ICON_NETWORK_SCAN,
    FUI_ICON_PAIRED_DEVICES,
    FUI_ICON_FLASH,
    FUI_ICON_SD_CARD,
    FUI_ICON_CAPACITY,
    FUI_ICON_BROWSE,
    FUI_ICON_FORMAT,
    FUI_ICON_USB_ROLE,
    FUI_ICON_USB_STORAGE,
    FUI_ICON_USB_AUDIO,
    FUI_ICON_USB_OUTPUT,
    FUI_ICON_USB_INPUT,
    FUI_ICON_USB_STATUS,
    FUI_ICON_CLOCK,
    FUI_ICON_TIMEZONE,
    FUI_ICON_LANGUAGE,
    FUI_ICON_KEYBOARD,
    FUI_ICON_ACCENT,
    FUI_ICON_OPACITY,
    FUI_ICON_BACKGROUND,
    FUI_ICON_WALLPAPER,
    FUI_ICON_PROCESSOR,
    FUI_ICON_ONCHIP_MEMORY,
    FUI_ICON_EXTERNAL_MEMORY,
    FUI_ICON_GPU2D,
    FUI_ICON_PERIPHERALS,
    FUI_ICON_PRODUCT,
    FUI_ICON_UI_ENGINE,
    FUI_ICON_RENDER_CONTRACT,
    FUI_ICON_SOFTWARE,
    FUI_ICON_RECORDINGS,
    FUI_ICON_FOLDER,
    FUI_ICON_FILE,
    FUI_ICON_LOADING,
    FUI_ICON_ERROR,
    FUI_ICON_STATUS_WIFI,
    FUI_ICON_STATUS_BLUETOOTH,
    FUI_ICON_QUICK_BRIGHTNESS,
    FUI_ICON_QUICK_ROTATION,

    FUI_ICON_COUNT
};

bool fui_icon_is_valid(fui_icon_id_t id);
bool fui_icon_draw(fui_painter_t *painter, fui_icon_id_t id,
                   fui_rect_t bounds, fui_color_t color);

#ifdef __cplusplus
}
#endif

#endif /* FEATHER_UI_ICONS_H */
