#ifndef FEATHERTALK_VERSION_H
#define FEATHERTALK_VERSION_H

#define FEATHERTALK_PRODUCT_VERSION      "0.1.0-dev"
#define FEATHERTALK_M33_FIRMWARE_VERSION "0.1.0-dev"
#define FEATHERTALK_M55_FIRMWARE_VERSION "0.1.0-dev"

#define FEATHERTALK_IPC_ABI_VERSION       1U

#endif /* FEATHERTALK_VERSION_H */
